=== idvr/mesa/java_apps/ObjectViewer/samples/sr_601ct.xsd
<?xml version="1.0"?>

<schema name="sr_601ct.xsd">

<!--        Content Values             -->
  <simpleType name="HAS CONCEPT MOD" base="string">
     <enumeration value="HAS CONCEPT MOD" />
  </simpleType>
  <simpleType name="CONTAINS" base="string">
     <enumeration value="CONTAINS" />
  </simpleType>
  <simpleType name="HAS OBS CONTEXT" base="string">
     <enumeration value="HAS OBS CONTEXT" />
  </simpleType>
  <simpleType name="CODE" base="string">
     <enumeration value="CODE" />
  </simpleType>
  <simpleType name="PNAME" base="string">
     <enumeration value="PNAME" />
  </simpleType>  
  <simpleType name="TEXT" base="string">
     <enumeration value="TEXT" />
  </simpleType>

  <!-- Coding Schemes -->
  <simpleType name="DCM" base="string">
     <enumeration value="DCM" />
  </simpleType>
  <simpleType name="LN" base="string">
     <enumeration value="LN" />
  </simpleType>
  <simpleType name="ISO369_1" base="string">
     <enumeration value="ISO369_1" />
  </simpleType>


  <simpleType name="Finding" base="string">
     <enumeration value="Finding" />
  </simpleType>
  <simpleType name="Findings" base="string">
     <enumeration value="Findings" />
  </simpleType>
  <simpleType name="History" base="string">
     <enumeration value="History" />
  </simpleType>
  <simpleType name="Conclusion" base="string">
     <enumeration value="Conclusion" />
  </simpleType>
  <simpleType name="Conclusions" base="string">
     <enumeration value="Conclusions" />
  </simpleType>

  <!-- Code Values -->
  <simpleType name="en" base="string">
     <enumeration value="en" />
  </simpleType>
  <simpleType name="xxx049" base="string">
     <enumeration value="xxx049" />
  </simpleType>
  <simpleType name="xxx008" base="string">
     <enumeration value="xxx008" />
  </simpleType>
  <simpleType name="xxx005" base="string">
     <enumeration value="xxx005" />
  </simpleType>
  <simpleType name="121060" base="string">
     <enumeration value="121060" />
  </simpleType>
  <simpleType name="121071" base="string">
     <enumeration value="121071" />
  </simpleType>
  <simpleType name="121077" base="string">
     <enumeration value="121077" />
  </simpleType>
  <simpleType name="121076" base="string">
     <enumeration value="121076" />
  </simpleType>

<!--         Header Values             --> 
  <simpleType name="PatientName" base="string">
     <enumeration value="SMITH^HAROLD" />
  </simpleType>
  <simpleType name="PatientID" base="string">
     <enumeration value="PIKR750000" />
  </simpleType>
  <simpleType name="PatientSex" base="string">
     <enumeration value="M" />
  </simpleType>
  <simpleType name="AccessionNumber" base="string">
     <enumeration value="PIKR0003" />
  </simpleType>
  <simpleType name="StudyInstanceUID" base="string">
     <enumeration value="2.16.840.1.113662.2.1.53544936282433.12345.336.16650" />
  </simpleType>
  <simpleType name="RequestedProcedureID" base="string">
     <enumeration value="xxx" />
  </simpleType>
  <simpleType name="CompletionFlag" base="string">
     <enumeration value="COMPLETE" />
  </simpleType>
  <simpleType name="VerificationFlag" base="string">
     <enumeration value="UNVERIFIED" />
  </simpleType>   
  <simpleType name="Modality" base="string"> 
     <enumeration value="SR" />  
  </simpleType>

  <group name="ContentItem1" order="seq">
	<element name="PRC_Relationship_Type" type="HAS CONCEPT MOD"/>
	<element name="PRC_Value_Type" type="CODE"/>
	<element name="PRC_Concept-name_Code_Sequence">
	    <complexType>
		<element name="ID_Code_Value" type="xxx049"/>
		<element name="ID_Coding_Scheme_Designator" type="DCM"/>
		<element name="ID_Code_Meaning" type="Language of Content Item and Descendents"/>
	    </complexType>
	</element>
	<element name="PRC_Concept_Code_Sequence">
	    <complexType>
		<element name="ID_Code_Value" type="en"/>
		<element name="ID_Coding_Scheme_Designator" type="ISO369_1"/>
		<element name="ID_Code_Meaning" type="English"/>
	    </complexType>
	</element>
  </group>

  <group name="ContentItem2" order="seq">
	<element name="PRC_Relationship_Type" type="HAS OBS CONTEXT"/>
	<element name="PRC_Value_Type" type="CODE"/>
	<element name="PRC_Concept-name_Code_Sequence">
	    <complexType>
		<element name="ID_Code_Value" type="xxx005"/>
		<element name="ID_Coding_Scheme_Designator" type="DCM"/>
		<element name="ID_Code_Meaning" type="Observer Type"/>
	    </complexType>
	</element>
	<element name="PRC_Concept_Code_Sequence">
	    <complexType>
		<element name="ID_Code_Value" type="xxx006"/>
		<element name="ID_Coding_Scheme_Designator" type="DCM"/>
		<element name="ID_Code_Meaning" type="Person"/>
	    </complexType>
	</element>
  </group>

  <group name="ContentItem3" order="seq">
	<element name="PRC_Relationship_Type" type="HAS OBS CONTEXT"/>
	<element name="PRC_Value_Type" type="PNAME"/>
	<element name="PRC_Concept-name_Code_Sequence">
	    <complexType>
		<element name="ID_Code_Value" type="xxx008"/>
		<element name="ID_Coding_Scheme_Designator" type="DCM"/>
		<element name="ID_Code_Meaning" type="Person Observer Name"/>
	    </complexType>
	</element>
	<element name="PRC_Person_Name" type="MOORE^STEVE"/>
  </group>

  <group name="ContentItem4" order="seq">
	<element name="PRC_Relationship_Type" type="CONTAINS"/>
	<element name="PRC_Value_Type" type="CONTAINER"/>
	<element name="PRC_Concept-name_Code_Sequence">
	    <complexType>
		<element name="ID_Code_Value" type="121060"/>
		<element name="ID_Coding_Scheme_Designator" type="DCM"/>
		<element name="ID_Code_Meaning" type="History"/>
	    </complexType>
	</element>
	<element name="PRC_Content_Sequence">
	    <complexType>
		<element name="PRC_Relationship_Type" type="CONTAINS"/>
		<element name="PRC_Value_Type" type="TEXT"/>
		<element name="PRC_Concept-name_Code_Sequence">
	    	    <complexType>
			<element name="ID_Code_Value" type="121060"/>
			<element name="ID_Coding_Scheme_Designator" type="DCM"/>
			<element name="ID_Code_Meaning" type="History"/>
		    </complexType>
		</element>
		<element name="PRC_Text_Value" type="string"/>
	    </complexType>
	</element>
  </group>

  <group name="ContentItem5" order="seq">
	<element name="PRC_Relationship_Type" type="CONTAINS"/>
	<element name="PRC_Value_Type" type="CONTAINER"/>
	<element name="PRC_Concept-name_Code_Sequence">
	     <complexType>
		<element name="ID_Code_Value" type="121070"/>
		<element name="ID_Coding_Scheme_Designator" type="DCM"/>
		<element name="ID_Code_Meaning" type="Findings"/>
	     </complexType>
	</element>
	<element name="PRC_Content_Sequence">
             <complexType>
		<element name="PRC_Relationship_Type" type="CONTAINS"/>
		<element name="PRC_Value_Type" type="TEXT"/>
		<element name="PRC_Concept-name_Code_Sequence">
		     <complexType>
			<element name="ID_Code_Value" type="121071"/>
			<element name="ID_Coding_Scheme_Designator" type="DCM"/>
			<element name="ID_Code_Meaning" type="Finding"/>
		     </complexType>
		</element>
		<element name="PRC_Text_Value" type="string"/>
	     </complexType>
	</element>
  </group>

  <group name="ContentItem6" order="seq">
	<element name="PRC_Relationship_Type" type="CONTAINS"/>
	<element name="PRC_Value_Type" type="CONTAINER"/>
	<element name="PRC_Concept-name_Code_Sequence">
	     <complexType>
		<element name="ID_Code_Value" type="121076"/>
		<element name="ID_Coding_Scheme_Designator" type="DCM"/>
		<element name="ID_Code_Meaning" type="Conclusions"/>
	     </complexType>
	</element>
	<element name="PRC_Content_Sequence">
	     <complexType>
		<element name="PRC_Relationship_Type" type="CONTAINS"/>
		<element name="PRC_Value_Type" type="TEXT"/>
		<element name="PRC_Concept-name_Code_Sequence">
	     	    <complexType>
			<element name="ID_Code_Value" type="121077"/>
			<element name="ID_Coding_Scheme_Designator" type="DCM"/>
			<element name="ID_Code_Meaning" type="Conclusion"/>
		    </complexType>
		</element>
		<element name="PRC_Text_Value" type="string"/>
	     </complexType>
	</element>
  </group>

  <element name="PRC_Content_Sequence">
   	<complexType>
	  <all>
	    <group ref="ContentItem1"/>
	    <group ref="ContentItem2"/>
	    <group ref="ContentItem3"/>
	    <group ref="ContentItem4"/>
	    <group ref="ContentItem5"/>
	    <group ref="ContentItem6"/>
	  </all>
	</complexType>
  </element>

  <element name="Structured_Report">
     <complexType>		
	<element   name="ID_SOP_Class_UID"        minOccurs="0"	type="string"/>
   	<element   name="ID_SOP_Instance_UID"     minOccurs="0"	type="string"/>
  	<element   name="ID_Study_Date"	          minOccurs="1"	type="string"/>
  	<element   name="ID_Image_Date"	          minOccurs="0" type="string"/>
  	<element   name="ID_Study_Time"           minOccurs="1"	type="string"/>
  	<element   name="ID_Image_Time"	          minOccurs="0"	type="string"/>
  	<element   name="ID_Accession_Number"     minOccurs="1" type="string"/>
  	<element   name="ID_Modality"	          minOccurs="1" type="Modality"/>
  	<element   name="ID_Manufacturer"	  minOccurs="1" type="string"/>
  	<element   name="ID_Referring_Physician_s_Name" minOccurs="1"	type="string"/>
	<element   name="PAT_Patient_Name"	  minOccurs="1" type="PatientName"/>
	<element   name="PAT_Patient_ID"	  minOccurs="1" type="PatientID"/>
  	<element   name="PAT_Patient_Birthdate"	  minOccurs="1" type="string"/>
  	<element   name="PAT_Patient_Sex"	  minOccurs="1" type="PatientSex"/>
  	<element   name="REL_Study_Instance_UID"  minOccurs="1"	type="StudyInstanceUID"/>
  	<element   name="REL_Series_Instance_UID" minOccurs="1" type="string"/>
  	<element   name="REL_Study_ID"	          minOccurs="1" type="string"/>
	<element   name="REL_Series_Number"	  minOccurs="1" type="string"/>
	<element   name="REL_Image_Number"        minOccurs="1" type="string"/>
	<element   name="PRC_Value_Type"          type="string"/>
	<element   ref="PRC_Concept-name_Code_Sequence"/>
	<element   ref="PRC_Verifying_Observer_Sequence"/>
	<element   name="PRC_Completion_Flag"	  type="string"/>
	<element   name="PRC_Verification_Flag"   type="string"/>
	<element   ref="PRC_Content_Sequence"/>
     </complexType>
  </element>

</schema>

=== idvr/mesa/java_apps/ObjectViewer/samples/sr_601ct.xml
<?xml version="1.0" ?>
<Structured_Report xmlns:xsi="http://www.w3.org/1999/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sr_601ct.xsd">
	<ID_Study_Date>19950126</ID_Study_Date>
	<ID_Image_Date>20010318</ID_Image_Date>
	<ID_Study_Time>094201.590</ID_Study_Time>
	<ID_Image_Time>041500.0000 </ID_Image_Time>
	<ID_Accession_Number>PIKR0003</ID_Accession_Number>
	<ID_Modality>SR</ID_Modality>
	<ID_Manufacturer>MIR</ID_Manufacturer>
	<ID_Referring_Physician_s_Name>####</ID_Referring_Physician_s_Name>
	<ID_Referenced_Study_Component_Sequence>
	</ID_Referenced_Study_Component_Sequence>
	<PAT_Patient_Name>SMITH^HAROLD</PAT_Patient_Name>
	<PAT_Patient_ID>PIKR750000</PAT_Patient_ID>
	<PAT_Patient_Birthdate>####</PAT_Patient_Birthdate>
	<PAT_Patient_Sex>M</PAT_Patient_Sex>
	<REL_Study_Instance_UID>2.16.840.1.113662.2.1.53544936282433.12345.336.16650</REL_Study_Instance_UID>
	<REL_Series_Instance_UID>zzz</REL_Series_Instance_UID>
	<REL_Study_ID>1665</REL_Study_ID>
	<REL_Series_Number>zzz</REL_Series_Number>
	<REL_Image_Number>12345</REL_Image_Number>
	<PRC_Value_Type>CONTAINER</PRC_Value_Type>
	<PRC_Concept-name_Code_Sequence>
		<ID_Code_Value>18747-6</ID_Code_Value>
		<ID_Coding_Scheme_Designator>LN</ID_Coding_Scheme_Designator>
		<ID_Code_Meaning>CT Report</ID_Code_Meaning>
	</PRC_Concept-name_Code_Sequence>
	<PRC_Completion_Flag_Description>COMPLETE</PRC_Completion_Flag_Description>
	<PRC_Verification_Flag>UNVERIFIED</PRC_Verification_Flag>
	<PRC_Content_Template_Sequence>
		<ID_Mapping_Resource>DCMR</ID_Mapping_Resource>
		<PRC_Template_Identifier>2000</PRC_Template_Identifier>
	</PRC_Content_Template_Sequence>
	<PRC_Content_Sequence>
		<PRC_Relationship_Type>HAS CONCEPT MOD </PRC_Relationship_Type>
		<PRC_Value_Type>CODE</PRC_Value_Type>
		<PRC_Concept-name_Code_Sequence>
			<ID_Code_Value>xxx049</ID_Code_Value>
			<ID_Coding_Scheme_Designator>DCM </ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>Language of Content Item and Descendents</ID_Code_Meaning>
		</PRC_Concept-name_Code_Sequence>
		<PRC_Concept_Code_Sequence>
			<ID_Code_Value>en</ID_Code_Value>
			<ID_Coding_Scheme_Designator>ISO369_l</ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>English </ID_Code_Meaning>
		</PRC_Concept_Code_Sequence>
		<PRC_Relationship_Type>HAS OBS CONTEXT </PRC_Relationship_Type>
		<PRC_Value_Type>CODE</PRC_Value_Type>
		<PRC_Concept-name_Code_Sequence>
			<ID_Code_Value>xxx005</ID_Code_Value>
			<ID_Coding_Scheme_Designator>DCM </ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>Observer Type</ID_Code_Meaning>
		</PRC_Concept-name_Code_Sequence>
		<PRC_Concept_Code_Sequence>
			<ID_Code_Value>xxx006</ID_Code_Value>
			<ID_Coding_Scheme_Designator>DCM</ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>Person</ID_Code_Meaning>
		</PRC_Concept_Code_Sequence>
		<PRC_Relationship_Type>HAS OBS CONTEXT </PRC_Relationship_Type>
		<PRC_Value_Type>PNAME</PRC_Value_Type>
		<PRC_Concept-name_Code_Sequence>
			<ID_Code_Value>xxx008</ID_Code_Value>
			<ID_Coding_Scheme_Designator>DCM</ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>Person Observer Name</ID_Code_Meaning>
		</PRC_Concept-name_Code_Sequence>
		<PRC_Person_Name>MOORE^STEVE </PRC_Person_Name>
		<PRC_Relationship_Type>CONTAINS</PRC_Relationship_Type>
		<PRC_Value_Type>CONTAINER</PRC_Value_Type>
		<PRC_Concept-name_Code_Sequence>
			<ID_Code_Value>121060</ID_Code_Value>
			<ID_Coding_Scheme_Designator>DCM </ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>History</ID_Code_Meaning>
		</PRC_Concept-name_Code_Sequence>
		<PRC_Content_Sequence>
			<PRC_Relationship_Type>CONTAINS</PRC_Relationship_Type>
			<PRC_Value_Type>TEXT</PRC_Value_Type>
			<PRC_Concept-name_Code_Sequence>
				<ID_Code_Value>121060</ID_Code_Value>
				<ID_Coding_Scheme_Designator>DCM </ID_Coding_Scheme_Designator>
				<ID_Code_Meaning>History</ID_Code_Meaning>
			</PRC_Concept-name_Code_Sequence>
			<PRC_Text_Value>46-year-old male presented to the emergency room with parasternal</PRC_Text_Value>
		</PRC_Content_Sequence>
		<PRC_Relationship_Type>CONTAINS</PRC_Relationship_Type>
		<PRC_Value_Type>CONTAINER </PRC_Value_Type>
		<PRC_Concept-name_Code_Sequence>
			<ID_Code_Value>121070</ID_Code_Value>
			<ID_Coding_Scheme_Designator>DCM </ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>Findings</ID_Code_Meaning>
		</PRC_Concept-name_Code_Sequence>
		<PRC_Content_Sequence>
			<PRC_Relationship_Type>CONTAINS</PRC_Relationship_Type>
			<PRC_Value_Type>TEXT</PRC_Value_Type>
			<PRC_Concept-name_Code_Sequence>
				<ID_Code_Value>121071</ID_Code_Value>
				<ID_Coding_Scheme_Designator>DCM</ID_Coding_Scheme_Designator>
				<ID_Code_Meaning>Finding</ID_Code_Meaning>
			</PRC_Concept-name_Code_Sequence>
			<PRC_Text_Value>There is an aneurysm of the entire thoracic aorta measuring up to 6.X/G </PRC_Text_Value>
		</PRC_Content_Sequence>
		<PRC_Relationship_Type>CONTAINS</PRC_Relationship_Type>
		<PRC_Value_Type>CONTAINER</PRC_Value_Type>
		<PRC_Concept-name_Code_Sequence>
			<ID_Code_Value>121076</ID_Code_Value>
			<ID_Coding_Scheme_Designator>DCM</ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>Conclusions</ID_Code_Meaning>
		</PRC_Concept-name_Code_Sequence>
		<PRC_Content_Sequence>
			<PRC_Relationship_Type>CONTAINS</PRC_Relationship_Type>
			<PRC_Value_Type>TEXT</PRC_Value_Type>
			<PRC_Concept-name_Code_Sequence>
				<ID_Code_Value>121077</ID_Code_Value>
				<ID_Coding_Scheme_Designator>DCM</ID_Coding_Scheme_Designator>
				<ID_Code_Meaning>Conclusion</ID_Code_Meaning>
			</PRC_Concept-name_Code_Sequence>
			<PRC_Text_Value>Aneurysm of thoracic aorta with dissection affecting ascending and d8DG</PRC_Text_Value>
		</PRC_Content_Sequence>
	</PRC_Content_Sequence>
</Structured_Report>
