=== idvr/mesa/java_apps/ObjectViewer/samples/TID2000.xsd
<?xml version="1.0"?>

<schema name="TID2000.xsd">

<!--  ************  SEQUENCES *************** -->

  <element name="PRC_Concept-name_Code_Sequence">
     <complexType>
  	<element   name="ID_Code_Value"      type="string"/>
  	<element   name="ID_Coding_Scheme_Designator"    type="string"/>
  	<element   name="ID_Code_Meaning"   type="string"/>
     </complexType>
  </element>

  <element name="PRC_Concept_Code_Sequence">
     <complexType>
  	<element   name="ID_Code_Value"      type="string"/>
  	<element   name="ID_Coding_Scheme_Designator"    type="string"/>
  	<element   name="ID_Code_Meaning"   type="string"/>
     </complexType>
  </element>

  <element name="PRC_Verifying_Observer_Sequence">
     <complexType>
  	<element   name="PRC_Verifying_Organization"      type="string"/>
  	<element   name="PRC_Verification_DateTime"       type="string"/>
  	<element   name="PRC_Verifying_Observer_Name"     type="string"/>
	<element   ref="PRC_Verifying_Observer_Identification_Code_Seq"/>
     </complexType>
  </element>

  <element name="PRC_Verifying_Observer_Identification_Code_Seq">
     <complexType>
	<element   name="ID_Code_Value"  type="string"/>
	<element   name="ID_Coding_Scheme_Designator" type="string"/>
	<element   name="ID_Code_Meaning"  type="string"/>
     </complexType>
  </element>

  <element name="PRC_Content_Sequence">
     <complexType>
	<group ref="ContentItem1" minOccurs='0' maxOccurs='unbounded'/>
	<group ref="ContentItem2" minOccurs='0' maxOccurs='unbounded'/>
	<group ref="ContentItem3" minOccurs='0' maxOccurs='unbounded'/>
	<group ref="ContentItem4" minOccurs='0' maxOccurs='unbounded'/>
     </complexType>
  </element>

<!--  *************  GROUPS (Content Items) *******************  -->

  <group name="ContentItem1">
    <all>
     <element name="PRC_Relationship_Type"	type="string"/>
     <element name="PRC_Value_Type"             type="string"/>
     <element ref="PRC_Concept-name_Code_Sequence"/>
     <element ref="PRC_Concept_Code_Sequence"/>
    </all>
  </group>

  <group name="ContentItem2" order="seq">
     <element name="PRC_Relationship_Type"	type="string"/>
     <element name="PRC_Value_Type"             type="string"/>
     <element ref="PRC_Concept-name_Code_Sequence"/>
     <element name="PRC_Person_Name"            type="string"/>
  </group>

  <group name="ContentItem3" order="seq">
     <element name="PRC_Relationship_Type"	type="string"/>
     <element name="PRC_Value_Type"  type="string"/>
     <element ref="PRC_Concept-name_Code_Sequence"/>
     <element name="PRC_Text_Value"             type="string"/>
  </group>

  <group name="ContentItem4" order="seq">
     <element name="PRC_Relationship_Type"	type="string"/>
     <element name="PRC_Value_Type"             type="string"/>
     <element ref="PRC_Concept-name_Code_Sequence"/>
     <element ref="PRC_Content_Sequence"/>
  </group>

   
  <simpleType name="Modality" base="string"> 
     <enumeration value="MR" /> 
     <enumeration value="CT" /> 
     <enumeration value="US" />
     <enumeration value="SR" /> 
  </simpleType>

<!--  *************  MAIN  ********************  -->

  <element name="Structured_Report">
     <complexType>	
	<element   name="ID_SOP_Class_UID"        type="string"/>
   	<element   name="ID_SOP_Instance_UID"     type="string"/>
  	<element   name="ID_Study_Date"	          type="string"/>
  	<element   name="ID_Image_Date"	          type="string"/>
  	<element   name="ID_Study_Time"           type="string"/>
  	<element   name="ID_Image_Time"	          type="string"/>
  	<element   name="ID_Accession_Number"     type="string"/>
  	<element   name="ID_Modality"	          type="Modality"/>
  	<element   name="ID_Manufacturer"	  type="string"/>
  	<element   name="ID_Referring_Physician_s_Name"	type="string"/>
	<element   name="PAT_Patient_Name"	fixed="bob"	  type="string"/>
	<element   name="PAT_Patient_ID"	  type="string"/>
  	<element   name="PAT_Patient_Birthdate"	  type="string"/>
  	<element   name="PAT_Patient_Sex"	  type="string"/>
  	<element   name="REL_Study_Instance_UID"  type="string"/>
  	<element   name="REL_Series_Instance_UID" type="string"/>
  	<element   name="REL_Study_ID"	          type="string"/>
	<element   name="REL_Series_Number"	  type="string"/>
	<element   name="REL_Image_Number"        type="string"/>
	<element   name="PRC_Value_Type"          type="string"/>
	<element   ref="PRC_Concept-name_Code_Sequence"/>
	<element   ref="PRC_Verifying_Observer_Sequence"/>
	<element   name="PRC_Completion_Flag"	  type="CompletionFlag"/>
	<element   name="PRC_Verification_Flag"   type="VerificationFlag"/>
	<element   ref="PRC_Content_Sequence"/>
     </complexType>
  </element>

</schema>

=== idvr/mesa/java_apps/ObjectViewer/samples/r1_simple_02.xml
<?xml version="1.0" ?>
<Structured_Report xmlns:xsi='http://www.w3.org/1999/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation='TID2000.xsd'>
	<ID_SOP_Class_UID>1.2.840.10008.5.1.4.1.1.88.11</ID_SOP_Class_UID>
	<ID_SOP_Instance_UID>1.113654.3.901.20</ID_SOP_Instance_UID>
	<ID_Study_Date>20000805</ID_Study_Date>
	<ID_Image_Date>20000805</ID_Image_Date>
	<ID_Study_Time>120100</ID_Study_Time>
	<ID_Image_Time>120100</ID_Image_Time>
	<ID_Accession_Number>MOF5023 </ID_Accession_Number>
	<ID_Modality>SR</ID_Modality>
	<ID_Manufacturer>IHE Labs</ID_Manufacturer>
	<ID_Referring_Physician_s_Name>NELL^FREDERICK^P^^DR</ID_Referring_Physician_s_Name>
	<PAT_Patient_Name>BROWN^JAMES </PAT_Patient_Name>
	<PAT_Patient_ID>M3030 </PAT_Patient_ID>
	<PAT_Patient_Birthdate>19501216</PAT_Patient_Birthdate>
	<PAT_Patient_Sex>M </PAT_Patient_Sex>
	<REL_Study_Instance_UID>1.113654.3.13.1046</REL_Study_Instance_UID>
	<REL_Series_Instance_UID>1.113654.2.901.10.2</REL_Series_Instance_UID>
	<REL_Study_ID>RP1023</REL_Study_ID>
	<REL_Series_Number>2 </REL_Series_Number>
	<REL_Image_Number>2 </REL_Image_Number>
	<PRC_Value_Type>CONTAINER </PRC_Value_Type>
	<PRC_Concept-name_Code_Sequence>
		<ID_Code_Value>1003</ID_Code_Value>
		<ID_Coding_Scheme_Designator>IHEY2 </ID_Coding_Scheme_Designator>
		<ID_Code_Meaning>MR Imaging of the Wrist </ID_Code_Meaning>
	</PRC_Concept-name_Code_Sequence>
	<PRC_Verifying_Observer_Sequence>
		<PRC_Verifying_Organization>Midwest Aviators</PRC_Verifying_Organization>
		<PRC_Verification_DateTime>20000805193000</PRC_Verification_DateTime>
		<PRC_Verifying_Observer_Name>PERRY^JOHN</PRC_Verifying_Observer_Name>
		<PRC_Verifying_Observer_Identification_Code_Seq>
			<ID_Code_Value>6060</ID_Code_Value>
			<ID_Coding_Scheme_Designator>IHEY2 </ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>PERRY^JOHN</ID_Code_Meaning>
		</PRC_Verifying_Observer_Identification_Code_Seq>
	</PRC_Verifying_Observer_Sequence>
	<PRC_Completion_Flag>PARTIAL </PRC_Completion_Flag>
	<PRC_Verification_Flag>UNVERIFIED</PRC_Verification_Flag>
	<PRC_Content_Sequence>
		<PRC_Relationship_Type>HAS OBS CONTEXT </PRC_Relationship_Type>
		<PRC_Value_Type>CODE</PRC_Value_Type>
		<PRC_Concept-name_Code_Sequence>
			<ID_Code_Value>5000</ID_Code_Value>
			<ID_Coding_Scheme_Designator>IHEY2 </ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>Observation Context Mode</ID_Code_Meaning>
		</PRC_Concept-name_Code_Sequence>
		<PRC_Concept_Code_Sequence>
			<ID_Code_Value>5000.1</ID_Code_Value>
			<ID_Coding_Scheme_Designator>IHEY2 </ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>DIRECT</ID_Code_Meaning>
		</PRC_Concept_Code_Sequence>
		<PRC_Relationship_Type>HAS OBS CONTEXT </PRC_Relationship_Type>
		<PRC_Value_Type>PNAME </PRC_Value_Type>
		<PRC_Concept-name_Code_Sequence>
			<ID_Code_Value>5010</ID_Code_Value>
			<ID_Coding_Scheme_Designator>IHEY2 </ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>Recording Observer Name </ID_Code_Meaning>
		</PRC_Concept-name_Code_Sequence>
		<PRC_Person_Name>MOORE </PRC_Person_Name>
		<PRC_Relationship_Type>HAS OBS CONTEXT </PRC_Relationship_Type>
		<PRC_Value_Type>TEXT</PRC_Value_Type>
		<PRC_Concept-name_Code_Sequence>
			<ID_Code_Value>5020</ID_Code_Value>
			<ID_Coding_Scheme_Designator>IHEY2 </ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>Recording Observer Organization Name</ID_Code_Meaning>
		</PRC_Concept-name_Code_Sequence>
		<PRC_Text_Value>MIR </PRC_Text_Value>
		<PRC_Relationship_Type>CONTAINS</PRC_Relationship_Type>
		<PRC_Value_Type>CONTAINER </PRC_Value_Type>
		<PRC_Concept-name_Code_Sequence>
			<ID_Code_Value>2002</ID_Code_Value>
			<ID_Coding_Scheme_Designator>IHEY2 </ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>"Procedure" </ID_Code_Meaning>
		</PRC_Concept-name_Code_Sequence>
		<PRC_Content_Sequence>
			<PRC_Relationship_Type>CONTAINS</PRC_Relationship_Type>
			<PRC_Value_Type>TEXT</PRC_Value_Type>
			<PRC_Concept-name_Code_Sequence>
				<ID_Code_Value>3003</ID_Code_Value>
				<ID_Coding_Scheme_Designator>IHEY2 </ID_Coding_Scheme_Designator>
				<ID_Code_Meaning>Procedure Text</ID_Code_Meaning>
			</PRC_Concept-name_Code_Sequence>
			<PRC_Text_Value>Standard XYZ Sequence applied to Left Wrist </PRC_Text_Value>
		</PRC_Content_Sequence>
		<PRC_Relationship_Type>CONTAINS</PRC_Relationship_Type>
		<PRC_Value_Type>CONTAINER </PRC_Value_Type>
		<PRC_Concept-name_Code_Sequence>
			<ID_Code_Value>2000</ID_Code_Value>
			<ID_Coding_Scheme_Designator>IHEY2 </ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>"Findings"</ID_Code_Meaning>
		</PRC_Concept-name_Code_Sequence>
		<PRC_Content_Sequence>
			<PRC_Relationship_Type>CONTAINS</PRC_Relationship_Type>
			<PRC_Value_Type>TEXT</PRC_Value_Type>
			<PRC_Concept-name_Code_Sequence>
				<ID_Code_Value>3000</ID_Code_Value>
				<ID_Coding_Scheme_Designator>IHEY2 </ID_Coding_Scheme_Designator>
				<ID_Code_Meaning>Findings Text </ID_Code_Meaning>
			</PRC_Concept-name_Code_Sequence>
			<PRC_Text_Value>We found this was a wrist.</PRC_Text_Value>
		</PRC_Content_Sequence>
		<PRC_Relationship_Type>CONTAINS</PRC_Relationship_Type>
		<PRC_Value_Type>CONTAINER </PRC_Value_Type>
		<PRC_Concept-name_Code_Sequence>
			<ID_Code_Value>2001</ID_Code_Value>
			<ID_Coding_Scheme_Designator>IHEY2 </ID_Coding_Scheme_Designator>
			<ID_Code_Meaning>"Conclusions" </ID_Code_Meaning>
		</PRC_Concept-name_Code_Sequence>
		<PRC_Content_Sequence>
			<PRC_Relationship_Type>CONTAINS</PRC_Relationship_Type>
			<PRC_Value_Type>TEXT</PRC_Value_Type>
			<PRC_Concept-name_Code_Sequence>
				<ID_Code_Value>3001</ID_Code_Value>
				<ID_Coding_Scheme_Designator>IHEY2 </ID_Coding_Scheme_Designator>
				<ID_Code_Meaning>Conclusion Text </ID_Code_Meaning>
			</PRC_Concept-name_Code_Sequence>
			<PRC_Text_Value>Everyone should have a left wrist </PRC_Text_Value>
		</PRC_Content_Sequence>
	</PRC_Content_Sequence>
</Structured_Report>
